version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defectdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/defectdb
      JWT_SECRET: supersecretkey
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      # Для простоты клиентских запросов в браузере используем host-порт
      API_URL: http://localhost:3000/api
    ports:
      - "3001:3000"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data:
